---
title: \vspace{8cm} \LARGE{Programme Evaluation of Maternal and Child Cash Transfer (MCCT) Programme in Kayah State, Myanmar}
subtitle: "Draft Report"
author: ""
date: "11 October 2019"
fontsize: 12pt
geometry: margin=2cm
documentclass: article
classoption: a4paper
bibliography: bibliography.bib
link-citations: TRUE
links-as-notes: FALSE
colorlinks: TRUE
linkcolor: blue
citecolor: blue
urlcolor: blue
lot: true
lof: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)

knitr::knit_hooks$set(document = function(x) {
  sub('\\usepackage[]{color}', '\\usepackage{xcolor}', x, fixed = TRUE)
  }
)

if(!require(rgdal)) install.packages("rgdal")
if(!require(rgeos)) install.packages("rgeos")
if(!require(raster)) install.packages("raster")
if(!require(maps)) install.packages("maps")
if(!require(knitr)) install.packages("knitr")
if(!require(kableExtra)) install.packages("kableExtra")
if(!require(magrittr)) install.packages("magrittr")
if(!require(FNN)) install.packages("FNN")
if(!require(ggplot2)) install.packages("ggplot2")
if(!require(ggmap)) install.packages("ggmap")
if(!require(stringr)) install.packages("stringr")
if(!require(remotes)) install.packages("remotes")
if(!require(openxlsx)) install.packages("openxlsx")
if(!require(RColorBrewer)) install.packages("RColorBrewer")
if(!require(magrittr)) install.packages("magrittr")

if(!require(myanmarMCCTdata)) install_github("validmeasures/myanmarMCCTdata")
if(!require(drlib)) install_github("dgrtwo/drlib")

waterLadder <- c("#4575b4", "#74add1", "#ffffbf", "#feb24c", "#ec7014")
sanitationLadder <- c("#1a9850", "#a6d96a", "#ffffbf", "#feb24c", "#ec7014")
handwashLadder <- c("#cab2d6", "#feb24c", "#ec7014")

themeSettings <- theme_bw() +
  theme(panel.border = element_rect(colour = "gray50",
                                    size = 0.5),
        panel.grid.major = element_line(linetype = 1,
                                        size = 0.1,
                                        colour = "gray90"),
        panel.grid.minor = element_line(linetype = 0),
        strip.background = element_rect(colour = "gray50",
                                        fill = "gray70"),
        strip.text = element_text(colour = "white", size = 16),
        legend.text = element_text(size = 16),
        legend.key = element_rect(linetype = 0, size = 3),
        legend.position = "top",
        axis.title = element_text(size = 16),
        axis.text.x = element_text(size = 14),
        axis.text.y = element_text(size = 14),
        axis.ticks = element_line(colour = "gray50", size = 0.5))
```

\newpage

# Acknowledgements {-}

\newpage

# Acronyms and abbreviations {-}

Acronym | Definition     
:--- | :---
CPI | Community Partners International
DSW | Department of Social Welfare
GAD | General Administration Department
GAM | Global acute malnutrition
HAZ | Height-for-age z-score
IYCF | Infant and young child feeding
MAM | Gobal acute malnutrition
MCCT | Mother and Child Cash Transfer
MMK | Myanmar Kyatt
MSWRR | Ministry of Social Welfare, Relief and Resettlement
MS-NPAN | Multi-Sector National Plan of Action for Nutrition
MUAC | Middle upper arm circumference
NNC | National Nutrition Council
NSPSP | National Social Protection Strategic Plan
ODK | Open Data Kit
RCT | Randomised controlled trial
RD | Regression discontinuity
SAM | Severe acute malnutrition
SBCC | Social Behavioural Change Communication
TEM | Technical error of measurement

\newpage

# Background {#background}

Kayah State remains one of the less developed areas of Myanmar and is home to some of the most remote and isolated communities in the country with decades long armed conflicts between Ethnic Armed Organizations and Myanmat Tatmadaw. As confirmed by Myanmar Demographic and Health Survey conducted in 2015, children in Kayah State are more likely to be malnourished than the average child in Myanmar, with the prevalence of stunting being particularly high [@MinistryofHealthandSports-MoHS/Myanmar2017]. Moreover, certain maternal and child health indicators are among the lowest in Myanmar, specifically concerning contraception prevalence, antenatal care visits as well as immunization rates amongst children 12 and 23 months of age.

Since 2017, the Ministry of Social Welfare, Relief and Resettlement (MSWRR) started rolling out a Maternal and Child Cash Transfer (MCCT) program in Chin, Rakhine, Kayah, and Kayin States through the Department of Social Welfare, in line with the National Social Protection Strategic Plan (NSPSP) and the Multi-Sector National Plan of Action for Nutrition (MS-NPAN). The program aims to improve nutritional outcomes for all mothers and children during the first 1000 days of life by ensuring that pregnant women and mothers have improved practices on nutrition, infant, and young child feeding, and health-seeking behaviors. The program aims to provide universal coverage to social behavior change communication (SBCC) and a maternal and child cash transfer (MCCT) of 15,000 MMK per month for all pregnant women and mothers with children under 2 years of age.

# Study aims and objectives {#objectives}

To provide a basis for measuring and evaluating the outcomes and impact of the MCCT program over time by estimating current levels of indicators related to:

1. Nutrition based on anthropometric measurements of maternal and child weight, height, and mid-upper arm circumference (MUAC) in Kayah State;

2. Behaviors related to nutrition, infant and young child feeding (IYCF), and health-seeking among mothers in Kayah State; and,

3. Knowledge related to health, nutrition, and hygiene among pregnant women and mothers with under five children in Kayah state.

## Research Questions {#research-questions}

1. What are the current levels of indicators related to nutrition, infant and young child feeding (IYCF), and health-seeking behaviors of mothers and under 5 children in Kayah State?

2. What is the impact of the MCCT program on child stunting in Kayah State?

3.  What is the impact of the MCCT program on maternal nutritional status in Kayah State?

## Study Output {#study-outputs}

1. Estimates of the current levels of indicators related to nutrition, IYCF, and health-seeking behaviors among mothers and their children under 5 in Kayah State

2. Estimate of prevalence of childhood stunting in the study cohort of children exposed to the MCCT program and those who are not in Kayah State

3. Estimate of prevalence of maternal nutritional status in the study cohort of mothers exposed to the MCCT program and those who are not in Kayah State

# Methods {#methods}

## Study design {#design}

The study included two primary components:

## Survey of selected households, villages, and townships {#study1}

This was composed of three surveys.

1. **Representative household survey** - The baseline survey was designed for the measurement and evaluation of outcomes over time by estimating the current levels of indicators related to nutrition, IYCF, and health-seeking behaviors. The baseline study was conducted during the roll-out of MCCT program in Kayah State.

2. **Village profiles** - Village level demographics, assets, and conditions were assessed in each of the selected villages in Kayah State.

3. **Township profiles** - Township profiles were developed from the township-level data collected from all townships in Kayah State from which sampled villages were from.

This component of the study was designed to address research question 1 (Section \@ref(research-questions)). The survey results were used to provide context to the results of the second study component (see Section \@ref(study2)).

### Sampling frame

To assess the various outcome indicators for the assessment[^1], a two-stage cluster sample survey was implemented. The **first stage sample** was a sample of about 75 villages out of the total villages in Kayah State stratified into 1) *urban*, 2) *rural* and 3) *hard-to-reach* areas. The **second stage sample**, also called the within-community sample, was a sample of households from the selected villages with mothers with children less than 5 years old. The second stage sample was selected using the list of household with children under 5 years of age from each village as identified by township General Administrative Unit (GAD) whenever possible.

A total of about 14 households with pregnant mothers and mothers with children less than 5 years were sampled in each village. If a small community was selected that was likely to have fewer than the required number of eligible respondents, all eligible households and persons in that community are sampled by moving door-to-door. If a household had more than one mother with children less than 5 years of age, mother with children less than 2 years of age was prioritized for data collection. If there were more than one mother with children less than 2 years of age, one of these mothers was selected randomly. Only the under 5 children of the index mother were included in the anthropometric measurements if there were more than one mother with under 5 children in the same household. In addition, all pregnant mothers present in the household of the respondents were measured for middle upper arm circumference (MUAC).

### Sample size estimation

Using childhood stunting as index indicator for sample size calculations, the sample size needed to detect a change of mean HAZ from 1.432 in Kayah State[^2] to -0.932 with a calculated standard deviation 1.14406[^2] was calculated. This is an equivalent drop in stunting prevalence of about 10%. This equates to a sample size of 137 children less than 5 years old. Assuming a design effect for a cluster survey of 2, this sample size was inflated to 274. A sample size of 274 respondents was needed for each strata (*urban*, *rural* and *hard-to-reach*) in Kayah State giving a total of 822 respondents in total. Assuming a non-response rate of 20% overall, a total of 330 respondents was the target sample for each strata in Kayah State.

As described in the sampling frame above, a total of 25 villages per strata and 14 respondent mothers with children less than 5 years old were the target number of samples and a total of 350 respondents in each strata was the overall target in order to achieve at least 274. In Kayah state, a total of 1050 respondents was the overall target. This is anticipated to be more than enough sample size as per calculations above. For the selected respondents who were not present at the time of data collection, two revisits were conducted with the respondent classified as a non-responder after two unsuccessful attempts.

## Quasi-experimental cohort study {#study2}

As part of a longitudinal, quasi-experimental evaluation design, the baseline survey included a cohort of mothers and their children selected through specific study eligibility criteria based on eligibility and receipt of the services and benefits of the MCCT program. Once recruited, this cohort was assessed on appropriate indicators related to nutrition, IYCF and health-seeking behaviours at baseline. This same cohort will then be assessed at endline on the same set of appropriate and relevant indicators to detect any difference between those receiving benefits from the MCCT from those who are not based on a regression discontinuity analytical approach (see Section \@ref(regression-discontinuity)).

This component of the study provides a statistically robust comparison between those exposed to the MCCT program and those who are not hence detecting the possible impact that the programme has on a specific set of impact indicators.

Given the universal nature of the MCCT program and the need to create effective treatment and comparison groups to detect program impact, this study component used a similar regression discontinuity (RD) design as was developed and used for the MCCT evaluation in Chin State, but with distinct changes that address limitations of the latter [@MinistryofSocialWelfareReliefandResettlement2018]. This design was made possible by the fact that there is a specific cut-off point for programme eligibility. Ultimately, the programme (treatment) effect can be detected as a discontinuity in the regression line around this cut-off which in this case is a specific date that determines eligibility. The design is *quasi-experimental*, since treatment and comparison groups were not selected at random but based on predefined characteristics.

### Eligibility criteria

Eligibility criteria depended on three factors:

* Date of start of recruitment into the MCCT program (1st October 2018)

* Date when the recruitment for study participants will occur (6th August 2019)

* Receipt of MCCT benefits

The optimal bandwidth of ages of the children to include in the study needed to be as close to the cut-off date as possible such that the ages of the children in the control and intervention groups will be roughly similarly distributed. This meant up to one month before and after the recruitment date of 1st October 2018. Given this, the following eligibility criteria were applied:

**Control group**

Following are the criteria for eligibility to the control group of the study:

1. Women who gave birth on/after 1 September 2018 but before 1 Oct 2108 (i.e. 1 month before the MCCT registration cut-off)

2. Women who were pregnant/gave birth after 1 Oct 2018 but have not been recruited into program

**Intervention group**

The criteria for eligibility to the intervention group of the study was women who were pregnant on or after 1 Oct 2018 and have been recruited into the program.

### Sample size and selection

The RD design effect was factored in for sample size calculations. This design effect was used to inflate standard randomized controlled trials (RCT) sample sizes in order to account for the RD design. The RD design effect was primarily influenced by the distribution of characteristics of the cut-off variable (i.e. running variable) [@Bor2014]. Previous literature advise that if the running variable is normally distributed around the cut-off, then the design effect is approximately 2.75. If the running variable is uniformly distributed around the cut-off, the design effect is 4, and if it is bimodal in distribution, then the design effect can go up to 5 [@Schochet2009].

Given that the running variable for this study is the start date of registration in relation to pregnancy, it was expected that there would be various peaks in number of pregnancies at specific time points following a general seasonal pattern not necessarily related to the cut-off date. The distribution is therefore likely multi-modal. So an assumption of at least 5 design effect for this RD design was taken into account.

Using prevalence of stunting as the index indicator for calculating sample size and using mean change in height-for-age z-score (HAZ) as the specific variable to use for assessing change, the same sample size calculation as in the survey was arrived at which was 137 for controls and 137 for intervention (total of 274) for each state.
However, given the very narrow bandwidth of inclusion into the study used (one month before and after the programme start), it is likely that the universe population from which to select the cohort is quite small and that the total sample size of 274 is likely requiring an exhaustive sampling of all children born within the specified periods above. In this case, the inflation factor to account for design effect was not considered to be relevant given that an exhaustive sample will be drawn to begin with. Hence the 274 sample size for Kayah State was set as the target sample size.

### Sample recruitment

Sample recruitment utilised a full list or registry of births one month before and after the 1st of October 2018. As an exhaustive sample was needed, all fforts were undertaken to identify and recruit into the study including engagement with the DSW in listing out and finding these births across Kayah state.

## Data collection

Data was collected using an electronic data entry system based on the **Open Data Kit (ODK)** standard that runs on the Android operating software (OS) platform for mobile devices. The study instrument (see Annex \@ref(annex1)) was encoded into the electronic data entry system platform and was served out of a secure aggregate server hosted by ONA[^3]. Each data collector was provided with a tablet running on Android OS that was configured with the ODK application that receives the electronic data form. All measurements and answers by respondents were then recorded on the tablets and transmitted to the remote server whenever there was a mobile and/or wireless internet signal. This data collection system was not reliant on internet connection as the data collection could be performed offline, with the completed e-questionnaires saved on the interviewers’ tablets. An internet connection was needed only when finalized encoded forms were ready to submit to the remote server, and this submission was done at regular intervals and timed when there was available internet connection for the data collectors. The survey teams aimed to submit forms on a daily basis.

### Questionnaire design:

Structured questionnaires for the household survey, village profiles, and township profiles were in English and translated into local languages. For the household survey, all questions and responses were translated into written Myanmar, Pwo Karen, and Sgaw Karen. The data collector had the option to switch from one language to another on the tablet. The household survey also included anthropometric measurements for weight, height and MUAC for all pregnant women, mothers who have recently given birth, and every child up to five years of age in selected households. A separate form was developed for the anthropometric measurements.

The village profile questionnaire assessed various village level characteristics relevant to the study such as number of and distances to nearby markets, education, and health facilities; presence of community groups (e.g., Village Health Committees) and their functionality; presence of community volunteers (e.g., auxiliary midwives and community health workers); access and quality of water and sanitation facilities; and general agricultural practices.

The township profile questionnaire collected data on the township’s population, geography, and governance, with summaries of key nutrition indicators.

All approved questionnaires were back-translated into English to ensure that appropriate translation was done with discrepancies between language versions discussed and resolved between the study team and translators. Prior to the start of data collection, the household survey questionnaire was pilot tested to understand how well the wording and content, context effects, and interface design of the instruments performed in an actual survey setting and were revised as necessary. Respondents for field testing were purposively sampled from the same population as the baseline assessment (e.g., mothers from the study area, village leaders). The recommended minimum of 32 respondents were recruited for field testing of the household questionnaire. Field testing was iterative with changes to the data collection instruments implemented immediately and the revised instrument was re-tested. Field testing involved feedback from the following three sources:

* Respondents: During field testing of the questionnaire, respondents were asked first to respond to the questions and then to re-interpret each question in their own words to learn how respondents understood the question and how they came up with their answers. The study team members probed for potential sources of ambiguity/confusion including word choice and translation, as well as the relevance and comprehensiveness of responses options to each question.
 
* Interviewers: The study team members provided feedback on the questionnaire content to confirm that questions and responses were clear in the context of data collection. Field testing also examined how well the e-questionnaire and tablet functioned in the field. Senior study team members collected data from enumerators for the purpose of field testing using a standardized debriefing questionnaire.

* Design and content experts: Members of the study team reviewed the data collected during the field testing phase to check whether the responses correspond to the meaning of individual questions and the overall goals of the study.

## Training of enumerators {#training}

Different trainings were conducted based on the skill that was being trained on and the type of personnel that was being trained.

### Anthropometric Training {#anthro-training}

Recruited anthropometrists received an intensive 5-day training from an expert anthropometric measurement trainer with supervision by National Nutrition Center (NNC) and nutrition advisor(s). The training covered an introduction to the purpose of the study, nutritional indicators , anthropometry, accuracy and validity of measurements, utilization and equipment of the measurement tools (e.g., MUAC tape, weighing scales, measuring board), and electronic data entry. The training emphasized practice and standardization of the anthropometric measurements to be used during the study according to methods adapted from the [WHO’s Multicentre Growth Reference Study](https://www.who.int/childgrowth/mgrs/en/) [@DeOnis2004] and [INTERGROWTH-21 Project](https://intergrowth21.tghn.org) [@Ismail2013] anthropometric training protocols. 

During the training, women of reproductive age and children under five years of age were invited to participate as subjects, and each subject was measured twice by the expert trainer serving as gold standard and twice by each trainee. To assess inter- and intra-rater precision, the technical error of measurement (TEM) was calculated, with an acceptable TEM for an individual trainee defined as no more than twice that of the expert [@ulijaszek_kerr_1999]. Accuracy was assessed by calculating mean differences between the gold standard trainer and the trainee. Only participants who meet the required standard for accuracy and precision were selected for anthropometric data collection during the baseline assessment. The training was conducted in Myanmar language.

### Interviewer and Supervisor Training {#interview-training}

All supervisors and enumerators received an intensive 5-day training from study team members that covered the purposes of the study, informed consent procedures, the questionnaire guides and responses, electronic data entry, referral protocols for severe acute malnutrition, roles and responsibilities of all field staff, data quality assurance procedures, problem-solving, and conflict-sensitive approaches to data collection. The performance of trainees were assessed post-training using a written assessment based on didactic lessons, as well as performance during practice sessions. Separate trainings were conducted for the supervisors and interviewers in Kayah State.

### Additional Supervisor Training {#add-training}

All supervisors received an additional 3 days of training from study team members that covered screening, random sampling method to identify respondents, quality control in the field, quality control of data entry and uploading, team management, and logistics.

## Survey management and supervision {#survy-management}

During data collection, 1 field supervisor supervised 1 team each composed of 4 enumerators and 2 anthropometrists. Each team was expected to complete 14 household interviews and one village profile per day depending on feasibility. Community Partners International worked with the Central NNC and State/Region Nutrition Teams and nutrition experts in developing a referral guideline and standard operating procedures to ensure that any women or children who were measured during the study and suspected of having severe acute malnutrition (SAM) were immediately referred to an appropriate health provider. Survey teams were provided with contact information of the nearest health providers to ensure timely referral. Alerts to refer women and children were programmed into the e-questionnaire on the ODK platform, based on WHO criteria for SAM.

## Quality control {#quality-control}

Quality control procedures throughout the assessment design, implementation, and analysis included:

* Translation, back-translation, and pilot testing as described above;

* Development of standard operating procedures and training manuals. CPI developed and distributed guidelines on data collection procedures, including the questionnaire and anthropometry methods, to all members of the data collection team;

* Training of data collectors where supervisors, enumerators, and anthropometrists practiced administering the questionnaire and checking and correcting questionnaires for accuracy and completeness. The performance of anthropometrists and data collectors were assessed in terms of confidence, independence, and reliability during practice sessions during the trainings, and based on results of an evaluation at the end of the training period;

* Anthropometric devices were calibrated and supervisors re-assessed some of the anthropometric measurements at intervals. Maintenance and quality check of all the other devices were done regularly as per the manufacturer’s instructions. Data collection was coordinated and continuously supervised by field supervisors and senior researchers.

* The data collection tool was designed in such a way that any potential errors related to data entry were minimized by programmatically adding data entry checks that raise appropriate prompts to the data collector based on the potential error detected. The data collector was not allowed by the system to continue to the next field until the error has been corrected. For the anthropometric measurements, a test for the feasibility of the measurements taken based on the child’s age and sex was implemented. If the measurement was above or below a certain threshold of feasible values, the system prompted the data collector to check their recording of the measurement, and to perform the measurement again. This approach was expected to pick up at least 90% of possible errors due to data entry and measurement errors. to complement this, an algorithm was added to randomly ask the data collector to repeat the measurement, even if the result of the first measurement was plausible. This approach was expected to pick up at least 90% of possible errors due to data entry and measurement errors.

* The Data Manager reviewed the data in real-time as they were uploaded to the server. This was done using a purpose-built application called `myanmarMCCTchecks`[^4] that allows for routine data checks automatically. In most cases, the error was detected and corrected immediately due to the data quality assurance measures built into the ODK platform, but if necessary, the interviewer was requested to revisit the respondent. In this case, the corrected questionnaire was uploaded and the wrong one deleted, so that only correct, checked records were stored in the database.

## Data processing and analysis {#analysis}

### Tools and methods {#processing-tools}

Data handling, processing, analysis and reporting were done using **version 3.6.1** of the [R Language for Statistical Computing](https://cran.r-project.org)[^5] [@R2019]. The R package **myanmarMCCTdata** was developed to support the handling, processing and analysis of data collected for the study. The package includes functions to retrieve data from the [ONA](https://ona.io) server database, to appropriately structure datasets, to check and clean data, to recode data to respective indicator sets, to estimate indicators and to perform appropriate comparative analysis specified by the analysis[^6] [@myanmarData2019]. The package uses several other R packages that provide additional functions for data processing, analysis and reporting[^7].

The main motivation for using R was to achieve transparent and reproducible research between the study collaborators and with external reviewers and/or readers. Developing the **myanmarMCCTdata** R package is the first step towards this aim of transparency and reproducibility as any collaborator and/or reviewer can easily retrieve the same codebase for data handling, processing and analysis used by the primary researchers. The second step was writing reports (including this report) using R itself using a seamless integration between data anlysis and reporting. This was achieved using R Markdown [@rmarkdown2018] for producting reports which included code chunks of how the data processed using **myanmarMCCTdata** functions were analysed to produce the results reported here. This report and the analysis herein, can be reviewed and reproduced by collaborators and reviewers by following instructions given [here](https://github.com/validmeasures/myanmarMCCTkayah).

### Indicator estimation {#indicator-estimation}

Indicators 



### Regression discontinuity {#regression-discontinuity}

\newpage


# Results {#results}

\newpage

# Annex 1: Study questionnaires {-}

This goes here. What else?

\newpage

# Annex 2: Anthropometric standardisation results {-}

Standardisation results here

\newpage

# References {-}








[^1]: Based on the earlier Chin assessment and based on feedback from various stakeholders.

[^2]: Based on 2015 Myanmar Demographic and Health Survey [@MinistryofHealthandSports-MoHS/Myanmar2017]

[^3]: See https://ona.io

[^4]: See https://validmeasures.io/myanmarMCCTchecks

[^5]: Can be downloaded from the [Comprehensive R Archive Network](https://cran.r-project.org) where guidance on installing R is also available.

[^6]: See https://validmeasures.org/myanmarMCCTdata to learn more about the **myanmarMCCTdata** package and how data is handled and processed using this package.

[^7]: For a full list of other R packages that **myanmarMCCTdata** depends on, see https://validmeasures.org/myanmarMCCTdata




